# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\ATC\WPATC\自动执行UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1051, 502)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.select = QtWidgets.QPushButton(Form)
        self.select.setObjectName("select")
        self.verticalLayout.addWidget(self.select)
        self.refresh = QtWidgets.QPushButton(Form)
        self.refresh.setObjectName("refresh")
        self.verticalLayout.addWidget(self.refresh)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.Filetree = QtWidgets.QTreeWidget(Form)
        self.Filetree.setObjectName("Filetree")
        self.horizontalLayout.addWidget(self.Filetree)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Run = QtWidgets.QPushButton(Form)
        self.Run.setObjectName("Run")
        self.verticalLayout_2.addWidget(self.Run)
        self.Resultcheck = QtWidgets.QPushButton(Form)
        self.Resultcheck.setObjectName("Resultcheck")
        self.verticalLayout_2.addWidget(self.Resultcheck)
        self.Clear = QtWidgets.QPushButton(Form)
        self.Clear.setObjectName("Clear")
        self.verticalLayout_2.addWidget(self.Clear)
        self.Savelog = QtWidgets.QPushButton(Form)
        self.Savelog.setObjectName("Savelog")
        self.verticalLayout_2.addWidget(self.Savelog)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.Logbrowser = QtWidgets.QTextBrowser(Form)
        self.Logbrowser.setMinimumSize(QtCore.QSize(500, 0))
        self.Logbrowser.setObjectName("Logbrowser")
        self.horizontalLayout.addWidget(self.Logbrowser)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.select.setText(_translate("Form", "选择脚本目录"))
        self.refresh.setText(_translate("Form", "刷新脚本列表"))
        self.Filetree.headerItem().setText(0, _translate("Form", "文件名"))
        self.Run.setText(_translate("Form", "开始运行"))
        self.Resultcheck.setText(_translate("Form", "Log/结果"))
        self.Clear.setText(_translate("Form", "清空窗口"))
        self.Savelog.setText(_translate("Form", "保存Log"))
